name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      run: docker build -t carboncounter:${GITHUB_SHA} .
    - name: Tests
      run: |
          docker run --rm -i \
            -w /opt/carbon-counter \
            -v `pwd`/tests:/opt/carbon-counter/tests \
            -v `pwd`/.ci/tests_entrypoint.sh:/tests_entrypoint.sh \
            --entrypoint /tests_entrypoint.sh \
            carbon-counter:${GITHUB_SHA}
        
